PUT http://localhost:8085/employees/10
Content-Type: application/json

{
  "id": 10,
  "name": "Michal",
  "username": "Rutowicz",
  "email": "mrut@gmail.com",
  "jobposition": "Backed",
  "salary": 10
}

